package com.fixtureservicexyz.utils

object StrKeys {
    const val SIGN_IN_USER_NAME = "USERNAME"
    const val SIGN_IN_PASSWORD = "PASSWORD"
    const val SIGN_UP_PERSONAL_DATA = "PERSONAL_DATA"
    const val SIGN_UP_PERSONAL_DATA_wITH_ADDRESS = "COMPLETE_USER_TO_REGISTER"
    const val SIGN_IN_AS_GUEST_PHONE_NUMBER = "GUEST_PHONE_NUMBER"
    const val SIGN_IN_AS_GOOGLE_ACCOUNT_EMAIL = "SIGN_IN_AS_GOOGLE_ACCOUNT_EMAIL"

    //SHARED PREFERENCES NAME
    const val SHARED_PREFERENCES_DB_REGISTER_USER = "SHARED_PREFERENCES_DB_NAME"
    const val SHARED_PREFERENCES_DB_GUEST = "SHARED_PREFERENCES_DB_NAME"

    // KEY FOR USER REGISTERED
    const val LOGGED_STATUS_SHARED_PREFS = "USER_STATUS"
    const val USER_REGISTERED_STATUS_SHARED_PREFS = "USER_REGISTERED"
    const val GUEST_STATUS_SHARED_PREFS = "GUEST"
    const val GOOGLE_STATUS_SHARED_PREFS = "GOOGLE"

    //USER REGISTERED
    const val USER_FULL_NAME_SHARED_PREFS = "USER_FULL_NAME"
    const val USER_EMAIL_SHARED_PREFS = "USER_EMAIL"
    const val USER_PHONE_SHARED_PREFS = "USER_PHONE"
    const val USER_NAME_SHARED_PREFS = "USER_NAME"
    const val USER_PASS_SHARED_PREFS = "USER_PASS"

    //GUEST
    const val GUEST_PHONE_NUMBER_SHARED_PREFS = "PHONE_NUMBER"

    //GOOGLE
    const val GOOGLE_EMAIL_SHARED_PREFS = "GOOGLE_EMAIL_SHARED_PREFS"

    //ADDRESS
    const val APARTMENT_ADDRESS_SHARED_PREFS = "APARTMENT_ADDRESS"
    const val STREET_ADDRESS_SHARED_PREFS = "STREET_ADDRESS"
    const val CITY_ADDRESS_SHARED_PREFS = "CITY_ADDRESS"
    const val PROVINCE_ADDRESS_SHARED_PREFS = "PROVINCE_ADDRESS"
    const val ZIP_CODE_ADDRESS_SHARED_PREFS = "ZIP_CODE_ADDRESS"

    //PLUMBING SERVICE SELECTED
    const val PLUMBING_SERVICE_SELECTED = "PLUMBING_SERVICE_SELECTED"
    const val ELECTRIC_SERVICE_SELECTED = "ELECTRIC_SERVICE_SELECTED"

    //Payment method
    const val PAYMENT_METHOD = "PAYMENT_METHOD"
    const val CREDIT_CARD_PAYMENT = "CREDIT_CARD_PAYMENT"
    const val DEBIT_CARD_PAYMENT = "DEBIT_CARD_PAYMENT"
}